name = "JuliaNiftyReg"
uuid = "ffddc5a0-8788-4ab8-a486-9604b72dd5c3"
authors = ["Wenbo Li <wenboli2016@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
